export type Emote = { ky: string; ten: string };

export type NhomEmote = { ten: string; muc: Emote[] };

/** Danh sách chọn khi bấm nút mặt. `ten` dùng cho ô tìm. */
export const NHOM_EMOTE: NhomEmote[] = [
  {
    ten: "Mặt",
    muc: [
      ["😀", "cười vui"],
      ["😁", "cười toe"],
      ["😂", "cười ra nước mắt"],
      ["🤣", "cười lăn"],
      ["😊", "cười hiền"],
      ["😍", "đôi mắt trái tim"],
      ["🥰", "yêu thích"],
      ["😘", "hôn"],
      ["😎", "đeo kính"],
      ["🤔", "suy nghĩ"],
      ["😅", "cười gượng"],
      ["😢", "khóc"],
      ["😭", "khóc to"],
      ["😡", "giận"],
      ["😴", "ngủ"],
      ["🤗", "ôm"],
      ["😉", "nháy mắt"],
      ["🙂", "cười nhẹ"],
      ["😇", "thiên thần"],
      ["🤩", "mắt sao"],
      ["😋", "ngon"],
      ["😜", "lè lưỡi"],
      ["🤪", "điên"],
      ["😏", "cười nhếch"],
      ["😒", "chán"],
      ["😞", "thất vọng"],
      ["😔", "buồn"],
      ["🥺", "nài nỉ"],
      ["😳", "ngượng"],
      ["🤯", "nổ đầu"],
      ["😱", "sợ"],
      ["😰", "lo"],
      ["🤢", "buồn nôn"],
      ["🤮", "nôn"],
      ["🤧", "hắt hơi"],
      ["🤒", "ốm"],
      ["🤕", "băng đầu"],
      ["🤠", "cao bồi"],
      ["🥳", "tiệc"],
      ["😑", "mặt vô cảm"],
      ["😬", "cau"],
      ["😮", "ngạc nhiên"],
      ["😯", "há miệng"],
      ["😲", "sốc"],
      ["🥱", "ngáp"],
      ["🤤", "thèm"],
      ["😷", "khẩu trang"],
      ["🤓", "mọt sách"],
      ["😈", "quỷ cười"],
      ["👻", "ma"],
      ["💀", "đầu lâu"],
      ["🤡", "chú hề"],
      ["👽", "người ngoài hành tinh"],
      ["🤖", "robot"],
    ],
  },
  {
    ten: "Cử chỉ",
    muc: [
      ["👍", "thích"],
      ["👎", "không thích"],
      ["👏", "vỗ tay"],
      ["🙏", "cảm ơn chắp tay"],
      ["🤝", "bắt tay"],
      ["👋", "vẫy tay"],
      ["✌️", "hai ngón"],
      ["🤞", "cầu may"],
      ["🤟", "yêu"],
      ["👌", "ok"],
      ["💪", "cơ bắp"],
      ["🙌", "giơ hai tay"],
      ["👀", "nhìn"],
      ["🧠", "não"],
    ],
  },
  {
    ten: "Trái tim",
    muc: [
      ["❤️", "tim đỏ"],
      ["🧡", "tim cam"],
      ["💛", "tim vàng"],
      ["💚", "tim xanh lá"],
      ["💙", "tim xanh"],
      ["💜", "tim tím"],
      ["🖤", "tim đen"],
      ["🤍", "tim trắng"],
      ["💔", "tim vỡ"],
      ["💕", "hai tim"],
      ["💖", "tim lấp lánh"],
      ["💘", "tim mũi tên"],
      ["💋", "nụ hôn"],
    ],
  },
  {
    ten: "Thiên nhiên",
    muc: [
      ["🌙", "trăng"],
      ["⭐", "sao"],
      ["✨", "lấp lánh"],
      ["🌟", "sao sáng"],
      ["☀️", "mặt trời"],
      ["🌈", "cầu vồng"],
      ["🔥", "lửa"],
      ["💧", "nước"],
      ["🍀", "cỏ bốn lá"],
      ["🌸", "hoa anh đào"],
      ["🌹", "hoa hồng"],
      ["🌻", "hướng dương"],
      ["🐱", "mèo"],
      ["🐶", "chó"],
      ["🐻", "gấu"],
      ["🐸", "ếch"],
      ["🦋", "bướm"],
    ],
  },
  {
    ten: "Đồ ăn",
    muc: [
      ["☕", "cà phê"],
      ["🍵", "trà"],
      ["🍕", "pizza"],
      ["🍔", "bánh burger"],
      ["🍰", "bánh ngọt"],
      ["🍓", "dâu"],
      ["🍉", "dưa hấu"],
      ["🍜", "mì"],
      ["🍣", "sushi"],
      ["🍫", "sô cô la"],
    ],
  },
  {
    ten: "Khác",
    muc: [
      ["🎉", "ăn mừng"],
      ["🎁", "quà"],
      ["💯", "một trăm"],
      ["✅", "đúng"],
      ["❌", "sai"],
      ["⚠️", "cảnh báo"],
      ["💬", "chat"],
      ["📞", "điện thoại"],
      ["📷", "máy ảnh"],
      ["🎵", "nhạc"],
      ["📚", "sách"],
      ["💡", "ý tưởng"],
      ["🎯", "mục tiêu"],
      ["🏆", "cúp"],
      ["💎", "kim cương"],
      ["🪙", "xu"],
      ["📌", "ghim"],
      ["⏰", "đồng hồ"],
      ["🚀", "tên lửa"],
      ["🪐", "hành tinh"],
    ],
  },
].map((nhom) => ({
  ten: nhom.ten,
  muc: nhom.muc.map(([ky, ten]) => ({ ky, ten })),
}));
