/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as ReaderHubRouteImport } from './routes/reader-hub'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadersIdRouteImport } from './routes/readers.$id'
import { Route as ProfileAstrologyRouteImport } from './routes/profile/astrology'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderHubRoute = ReaderHubRouteImport.update({
  id: '/reader-hub',
  path: '/reader-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersIdRoute = ReadersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReadersRoute,
} as any)
const ProfileAstrologyRoute = ProfileAstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => ProfileRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRouteWithChildren
  '/tarot': typeof TarotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/astrology': typeof ProfileAstrologyRoute
  '/readers/$id': typeof ReadersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRouteWithChildren
  '/tarot': typeof TarotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/astrology': typeof ProfileAstrologyRoute
  '/readers/$id': typeof ReadersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRouteWithChildren
  '/tarot': typeof TarotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/astrology': typeof ProfileAstrologyRoute
  '/readers/$id': typeof ReadersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/tarot'
    | '/blog/$slug'
    | '/profile/astrology'
    | '/readers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/tarot'
    | '/blog/$slug'
    | '/profile/astrology'
    | '/readers/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/tarot'
    | '/blog/$slug'
    | '/profile/astrology'
    | '/readers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ReaderRoute: typeof ReaderRoute
  ReaderHubRoute: typeof ReaderHubRoute
  ReadersRoute: typeof ReadersRouteWithChildren
  TarotRoute: typeof TarotRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader-hub': {
      id: '/reader-hub'
      path: '/reader-hub'
      fullPath: '/reader-hub'
      preLoaderRoute: typeof ReaderHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers/$id': {
      id: '/readers/$id'
      path: '/$id'
      fullPath: '/readers/$id'
      preLoaderRoute: typeof ReadersIdRouteImport
      parentRoute: typeof ReadersRoute
    }
    '/profile/astrology': {
      id: '/profile/astrology'
      path: '/astrology'
      fullPath: '/profile/astrology'
      preLoaderRoute: typeof ProfileAstrologyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileAstrologyRoute: typeof ProfileAstrologyRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileAstrologyRoute: ProfileAstrologyRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface ReadersRouteChildren {
  ReadersIdRoute: typeof ReadersIdRoute
}

const ReadersRouteChildren: ReadersRouteChildren = {
  ReadersIdRoute: ReadersIdRoute,
}

const ReadersRouteWithChildren =
  ReadersRoute._addFileChildren(ReadersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ReaderRoute: ReaderRoute,
  ReaderHubRoute: ReaderHubRoute,
  ReadersRoute: ReadersRouteWithChildren,
  TarotRoute: TarotRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
