/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TarotHistoryRouteImport } from './routes/tarot-history'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadersRouteImport } from './routes/readers'
import { Route as ReaderHubRouteImport } from './routes/reader-hub'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop_.$slug'
import { Route as ReadersIdRouteImport } from './routes/readers_.$id'
import { Route as ProfileAstrologyRouteImport } from './routes/profile_.astrology'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotHistoryRoute = TarotHistoryRouteImport.update({
  id: '/tarot-history',
  path: '/tarot-history',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersRoute = ReadersRouteImport.update({
  id: '/readers',
  path: '/readers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderHubRoute = ReaderHubRouteImport.update({
  id: '/reader-hub',
  path: '/reader-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop_/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadersIdRoute = ReadersIdRouteImport.update({
  id: '/readers_/$id',
  path: '/readers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAstrologyRoute = ProfileAstrologyRouteImport.update({
  id: '/profile_/astrology',
  path: '/profile/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/manager': typeof ManagerRoute
  '/profile': typeof ProfileRoute
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/tarot': typeof TarotRoute
  '/tarot-history': typeof TarotHistoryRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/astrology': typeof ProfileAstrologyRoute
  '/readers/$id': typeof ReadersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/manager': typeof ManagerRoute
  '/profile': typeof ProfileRoute
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/tarot': typeof TarotRoute
  '/tarot-history': typeof TarotHistoryRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile/astrology': typeof ProfileAstrologyRoute
  '/readers/$id': typeof ReadersIdRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/manager': typeof ManagerRoute
  '/profile': typeof ProfileRoute
  '/reader': typeof ReaderRoute
  '/reader-hub': typeof ReaderHubRoute
  '/readers': typeof ReadersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shop': typeof ShopRoute
  '/staff': typeof StaffRoute
  '/support': typeof SupportRoute
  '/tarot': typeof TarotRoute
  '/tarot-history': typeof TarotHistoryRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/profile_/astrology': typeof ProfileAstrologyRoute
  '/readers_/$id': typeof ReadersIdRoute
  '/shop_/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/home'
    | '/manager'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/reset-password'
    | '/shop'
    | '/staff'
    | '/support'
    | '/tarot'
    | '/tarot-history'
    | '/verify-email'
    | '/blog/$slug'
    | '/profile/astrology'
    | '/readers/$id'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/home'
    | '/manager'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/reset-password'
    | '/shop'
    | '/staff'
    | '/support'
    | '/tarot'
    | '/tarot-history'
    | '/verify-email'
    | '/blog/$slug'
    | '/profile/astrology'
    | '/readers/$id'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/home'
    | '/manager'
    | '/profile'
    | '/reader'
    | '/reader-hub'
    | '/readers'
    | '/reset-password'
    | '/shop'
    | '/staff'
    | '/support'
    | '/tarot'
    | '/tarot-history'
    | '/verify-email'
    | '/blog/$slug'
    | '/profile_/astrology'
    | '/readers_/$id'
    | '/shop_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  HomeRoute: typeof HomeRoute
  ManagerRoute: typeof ManagerRoute
  ProfileRoute: typeof ProfileRoute
  ReaderRoute: typeof ReaderRoute
  ReaderHubRoute: typeof ReaderHubRoute
  ReadersRoute: typeof ReadersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShopRoute: typeof ShopRoute
  StaffRoute: typeof StaffRoute
  SupportRoute: typeof SupportRoute
  TarotRoute: typeof TarotRoute
  TarotHistoryRoute: typeof TarotHistoryRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProfileAstrologyRoute: typeof ProfileAstrologyRoute
  ReadersIdRoute: typeof ReadersIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot-history': {
      id: '/tarot-history'
      path: '/tarot-history'
      fullPath: '/tarot-history'
      preLoaderRoute: typeof TarotHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers': {
      id: '/readers'
      path: '/readers'
      fullPath: '/readers'
      preLoaderRoute: typeof ReadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader-hub': {
      id: '/reader-hub'
      path: '/reader-hub'
      fullPath: '/reader-hub'
      preLoaderRoute: typeof ReaderHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop_/$slug': {
      id: '/shop_/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readers_/$id': {
      id: '/readers_/$id'
      path: '/readers/$id'
      fullPath: '/readers/$id'
      preLoaderRoute: typeof ReadersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/astrology': {
      id: '/profile_/astrology'
      path: '/profile/astrology'
      fullPath: '/profile/astrology'
      preLoaderRoute: typeof ProfileAstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  HomeRoute: HomeRoute,
  ManagerRoute: ManagerRoute,
  ProfileRoute: ProfileRoute,
  ReaderRoute: ReaderRoute,
  ReaderHubRoute: ReaderHubRoute,
  ReadersRoute: ReadersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShopRoute: ShopRoute,
  StaffRoute: StaffRoute,
  SupportRoute: SupportRoute,
  TarotRoute: TarotRoute,
  TarotHistoryRoute: TarotHistoryRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProfileAstrologyRoute: ProfileAstrologyRoute,
  ReadersIdRoute: ReadersIdRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
